# Generated by Django 2.2.6 on 2019-11-17 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('flex', '0004_auto_20190924_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='flexpage',
            name='flex_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
